<h1 style="font-size: 2.5em; font-weight: bold; margin-top: 0.5em; margin-bottom: 0.5em;">
First steps into Python
</h1>

<div class="alert alert-block alert-warning">
<b>Preparing for this assignment:</b>

The following resources will help you to get ready to complete this assignment. If you are comfortable programming Python, you can skip this.
<ul>
    <li>If you do not have experience programming in Python, here is a good tutorial to get you quickly on track: <a href="https://cogs18.github.io/intro.html" target="_blank">Introduction to Python</a> </li>
    <li>If you already know other languages and need a technical view of what is special about Python syntax, try <a href="https://en.wikipedia.org/wiki/Python_syntax_and_semantics#Indentation" target="_blank">this</a></li>
</ul>
</div>

There are two ways to run Python: either on the cloud (using Google Colab) or locally on your computer using Notebook. Either way if you are reading this, you are probably set to go. Just in case:
- To run code on **Google Colab**, you don't need to install anything on your machine since all the computations take place in the cloud.
- To run **Python Notebooks** locally, you either need to install Python 3 using Anaconda following [these](https://jupyter.readthedocs.io/en/latest/install.html) instructions or else use [myapps.upf.edu](https://myapps.upf.edu). You will find more detailed instructions in the [course site](https://github.com/wimmerlab/MBC_data_analysis) in GitHub.



# Getting started
## Importing libraries
The actions you can do with Python code are limitless, so you do not need all the tools at the same time. If you loaded all Python tools at once you would be taking up all your computer resources! That is why Python works with **libraries**.  

One library is a collection of functions that allows you to perform many actions.   
In other words, they have snippets of code created and tested by other people that you can quickly reuse, so you do not need to work as much.

Every time you start a new project, you will have to **import** the libraries you will use.  
The ones we will need for this assignment are:

[Numpy](https://en.wikipedia.org/wiki/NumPy) for manipulating numerical data.   
[Matplotlib](https://en.wikipedia.org/wiki/Matplotlib) for plotting graphics.

These are the default two libraries you will use on basicalle ALL your notebooks. Explore the links if you want to know more about them! :)

Let's start importing!

PS: remember to **execute** each of the cells with code below by clicking in the cell and press "Shift + Enter"

In [34]:
import numpy as np  # everytime we want to use a function from numpy, we will put np. before, e.g.: np.array()
import matplotlib.pyplot as plt  # same for function from matplotlib.pyplot, we will address them with plt. , e.g.: plt.plot()

We imported these two libraries, and we gave them shorter names to simplify our code. From now on, we can use the code contained in the library **numpy** by prefixing it with `np.` (for instance `np.pi` will give us the numerical value of the number $\pi$), and the code of the library **matplotlib.pyplot** with `plt` (for example: `plt.plot`)

Note that, in the first line of the code, there is some text after a `#`?   
This is a **comment**. Comments are really useful if someone else has to read your code. In a Python Notebook comments can come either after `#` in *code cells* or directly in a *markdown cell* which is entirely text (see all cells before this first *code cell*)

It will be much easier for other readers (and for you after some time) to understand your code if you comment your codes.
**Do not be lazy and comment!**.  

[Here](https://stackabuse.com/commenting-python-code/) you have some advice to do it wisely.


## Loading the data

When running data analyses, one of the first things to do is to load the data into our programming environment so we can manipulate it. Data will come in a specific format depending on how it was generated and saved. You will generally need to obtain this information from the person who generated the data.

One common format you might get the data in is in a tabular format, with measurements organized in a fixed number of rows and columns (a *matrix*). Let's load one of these datasets.

Now, you need to have the file: "Task_Perceptual_simple.csv" in the same directory as this file, or else know the exact path to this file. Below, we read the file from the online GitHub repository (using an URL). The line that is commented out shows how to read the file from a local directory.  
  
**One first question, what is in this file? (Hint: open it in a text editor or in GitHub)**

In [35]:
#load the file from github
data = np.genfromtxt("https://raw.githubusercontent.com/wimmerlab/MBC_data_analysis/main/A0_PythonBasics/Task_Perceptual_simple.csv", delimiter=',', skip_header=1)

If there are no errors.... congratulations! You have imported the data. Let's take a look!
### Inspecting arrays

In [36]:
data

array([[-10.      ,   0.      ,  -5.      ,  -5.2122  ,   1.      ],
       [-10.      , -10.      , -10.      ,  -8.21768 ,   1.      ],
       [ 20.      ,  10.      ,  15.      , -17.93416 ,   1.      ],
       ...,
       [ 10.      , -10.      ,   0.      ,  12.234593,  14.      ],
       [  0.      ,  10.      ,   5.      ,   8.8409  ,  14.      ],
       [-20.      ,   0.      , -10.      ,   9.943002,  14.      ]])

`data` is a matrix, how could you tell its dimensions (number of rows and colums)?
(Note: if you edit your code in environments such as Spyder instead of Notebook, you will find tools to explore directly all the variables created in a session)

Don't worry if you don't know right away... A really important thing you will learn as you are coding is to do "efficient" Google searches and to ask ChatGPT for help.
Everyone -- including your teachers when creating these templates -- have to search online from time to time when coding.  
***Do not get stressed about it!***  
At the beginning, it will take a long time to find simple stuff but as you keep coding, you will get used to
the language and you will learn what are the keywords you need to use for every search.

What if you start by searching: **"dimensions numpy matrix"** in Google or ask ChatGPT?

Write the command that results from your search in the next cell:

In [37]:
print(data.shape)

(13503, 5)


Now let's see if you did it right. The first number should tell you the number of rows, while the second number should tell you the number of columns.

Here is a little check that we can have our program do on our data using the command `assert`. This is useful to **debug** our code, when we want to check that things are as we want them to be in the process of developing the code. In our course, we will use this also to give you feedback as to whether you are generating reasonable code or if there is some error to correct. Try it now by replacing the placeholder `???` in the cell below with your answer for getting the matrix dimensions (cell above). Then execute the cell with *Shift + Enter*

In [38]:
assert data.shape[0] == 13503

If you did not get any output back, then you are good. If you did get a warning, then your code has some problem.

Ok, so now is the good time to tell you about the data! This is the behavioral data from one experiment in an influential paper studying the **confirmation bias in perceptual decisions**, by Talluri and colleagues ([link here](https://www.sciencedirect.com/science/article/pii/S0960982218309825)). The paradigm is illustrated in this [figure](https://ars.els-cdn.com/content/image/1-s2.0-S0960982218309825-gr1_lrg.jpg):
Each row of the array correspond to one trial in the dataset (the array concatenantes data from all participants). Each column represents a different variable in the task, respectively: the orientation of the first stimulus, the orientation of the second stimulus, the average orientation over both stimuli, the orientation provided by the subject at the end of the trial and the subject id. Note that the data here corresponds to the subset of trials where an intermediate judgment is provided and the subject was requested to provided the orientation at the end of the trial.

## Subsetting

A fundamental operation we will need to do on our data is to select parts of the data, some rows or some columns, to operate specifically on them. This selection of a subset of our data is what we call *subsetting*.

Just to get used to it, ***extract the first 10 rows of the 1st and 2nd column*** of your array **data**.   
Be careful, in Python the numbers start at 0, so the first row has the index 0.  
You can google by yourself how to do it or use [this](https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html) online handbook.   
Write the solution in the next cell.  

In [39]:
subset = data[:10, :2]
print(subset)

[[-10.   0.]
 [-10. -10.]
 [ 20.  10.]
 [-20.  10.]
 [ 20. -10.]
 [-20.   0.]
 [-20. -20.]
 [  0.  10.]
 [-20.  10.]
 [-10. -20.]]


But, what are these numbers? Well, you will explore them in depth in the next assignments.   
For now, we are just practicing basic skills, so it is enough to know that this is a psychophysics dataset of a perceptual decision making task where subjects have to estimate the average motion direction of two subsequent stimuli.   
Each row is one ***trial***, the first column contains the motion direction of the first stimulus ***x1*** and the second column the motion direction of stimulus ***x2***.  
Their units are degrees.
***What is the range of these values?***  
Hint: google for minimum and maximum values


In [40]:
max_value = np.max(subset)
min_value = np.min(subset)
print(max_value)
print(min_value)
range = max_value - min_value
print(range)


20.0
-20.0
40.0


The third column of the data is the average of x1 and x2, ***xavg***. Check is this is actually true by recomputing the avearage and comparing it to the third column.

In [41]:
# create vector as average of first two columns
xavg_recomputed = (data[:, 0] + data[:, 1]) / 2

# difference with third column
diff = xavg_recomputed - data[:, 2]
print(diff)

# maximum absolute difference (should be 0 IF AND ONLY IF all differences are zero) - NOTE: we could also use boolean arrays which are introduced below
max_abs_diff = np.abs(diff).max()
print(max_abs_diff)


[0. 0. 0. ... 0. 0. 0.]
0.0


## Subsetting with booleans

Sometimes it is convenient to use [booleans]().
This is typically just another Python array but, instead of containing numbers, it contains `True` and `False`. If you use a boolean to index another array you just get the values of this array that correspond to `True` values in the boolean.  
For example:

```
matrix = np.array([1, 2, 3, 4])
boolean = np.array([True, False, True, True])
```

If you apply the boolean to index the matrix this way
```
matrix[boolean]
```
you get a subset of the original array `matrix` only with corresponding `True` values in `boolean`:
```
array([1, 3, 4])
```

A boolean is something really simple to create, you just need to specify a [condition](https://www.w3schools.com/python/python_conditions.asp), for instance:

```
matrix = np.array([1, 1, 2, 2])
boolean = matrix==2
```
(notice the difference between `=`, an assignment, and `==`, a condition)

The boolean then will be:

```
array([False, False,  True,  True])
```
which indicates in what positions of array **matrix** the condition `==2` is satisfied

Let's now try this hands-on!

The 5th column of the matrix contains an integer number that identifies each specific subject that participated in the study. Let's now create a few new [variables](https://realpython.com/python-variables/) :

1.   Create the variable `nSubject` with the number of subjects that performed this task (Hint: Google **"python unique"**)
2.   Create the boolean `bool7` to mark the rows obtained from Subject #7
3.   Using `bool7` create the variable `subj7` that includes only the specific data of Subject #7


In [42]:
# 5th column = subject IDs
subject_list = data[:, 4].astype(int)

# number of elements in that list (corresponds to the number of subjects)
nSubject = np.unique(subject_list).size

print("number of subjects: ", nSubject)

number of subjects:  14


In [43]:
# create boolean array that is true for rows corresponding to subject 7
bool7 = (subject_list == 7)

# select data for subject 7 (i.e corresponding rows)
subj7 = data[bool7, :]

In [44]:
subj7.shape

(1000, 5)

In [45]:
assert nSubject == 14, "nSubject is incorrect"
assert np.sum(bool7) == 1000
assert np.shape(subj7)[0] == sum(bool7)
assert np.shape(subj7)[1] == 5
print(np.sum(bool7))

1000


If you ran the previous cell and it did not complain, you did a great job! If not, try running the different ```assert``` commands separately to debug more specifically your problem. **Remember that by preceding a whole sentence with a # you turn it into a comment and it is not executed as code!**

By the way, what is ```np.sum(bool7)```?



*italik metin*<u>Answer</u>: 1000

# Functions

Sometimes, in the libraries that we are using we do not have the specific function that we need.  
When that is the case, we have to create it by ourselves.  
Suppose, for instance, that we want to calculate the distance between the stimulus average (the third column of our data) and the response of the participant (stored in the forth column of our data) to get a measure of error. Distances can often be calculated as a mere difference, but here we are dealing with angles on a circle so that we have to take into account that the circle wraps around. We need a specific function to deal with this.
The function will be called ***circdist***.  

In [46]:
def circdist(angles1, angles2): # define the name and set the arguments between parentheses
    """
    Calculate the circular distance between two angles.

    Parameters:
        angles1 (float): First angle. Scalar or array.
        angles2 (float): First angle. Scalar or array.

    Returns:
        float: Angle difference(s).
    """
    angle_diff = angles1 - angles2 # angle difference
    angle_diff = angle_diff  / 180 * np.pi # convert to radian
    output = np.angle(np.exp(1j * angle_diff))  # mathematical operation to get the circular distance
    output = output / np.pi * 180   # convert back to degrees
    return output  # return the circular distance in radians

In this case, the operation we are performing in the function is quite complex but the structure of the code is very simple. Check it up carefully: the command **def**, the name of the function with arguments within parenthesis, the colon at the end of the line, the indentation for all commands that define the function and finally the **return** command with the result that the function returns. You can learn [here](https://www.tutorialspoint.com/python/python_functions.htm) more about functions in Python.

**Now use the circdist function to get the circular distance between the stimulus average and the response of the subject**. We will call this **error** as participants were supposed to respond the exact value of the target so any deviation from target is an "error".
Hint: use the link above and apply the "calling a function" to this specific case.

In [47]:
err = circdist(data[:, 2], data[:, 3])
err_first = err[0]
print(err_first)

0.2122000000000002


In [48]:
# array representing the distance between stimulus average and response for all trials
err = circdist(data[:, 2], data[:, 3])
print(err)

[  0.2122    -1.78232   32.93416  ... -12.234593  -3.8409   -19.943002]


The circular distance between the target and the response (error) could be a really useful measure to add to our matrix, right? That way we do not need to calculate it everytime.  

**Now try to add it as an extra column to the matrix**  *data* using the command `np.column_stack`.
You already have the tools to start flying alone (copilot, chatgpt, google, matrix subsetting, intuition...)!   
Do not be afraid! Try things!  
Let the "I am going to mess it up fear" go away! If, by any weird chance, you "destroy" your matrix, you just have to go to the top of this page and run everyting again, it will just take 1 second! Try it now.

In [49]:
data = np.column_stack((data, err))

In [50]:
assert data.shape[1] == 6

Great! Now you have one more column in your data array, which contains the angular error of responses in each trial. This is the last column of your array, and you can address that with the index "-1" in Python, so now `data[:,-1]` contains the values in **error**

# Plotting

Let's see how the errors look like!  
According to the literature they should follow a [Gaussian](https://en.wikipedia.org/wiki/Normal_distribution) distribution around 0.  
The visualization tool that best fits what we need is a [histogram](https://en.wikipedia.org/wiki/Histogram).  
Use matplotlib to plot a [histogram](https://matplotlib.org/3.3.3/api/_as_gen/matplotlib.pyplot.hist.html) of the new column of your matrix.
It would be nice if you could also plot a red vertical line at the mean value of errors and see if the results are in line with the assumption.  



In [51]:
# plot histogram with 100 bin counts
???
# add a red vertical line at the mean error (null error)
mean_error = ???
plt.axvline(???, color='red');

# add axis labels
plt.xlabel('behavioral error');
plt.ylabel('trial count');

SyntaxError: invalid syntax (ipython-input-2148296828.py, line 4)

# For loop

Now you will learn a really powerful tool: the ***for loop***.   
This tool allows you to make iterations, so you can run the same commands, over and over again without
having to write new code for each iteration.  

Check out the next two cells to understand why this is so useful:

In [ ]:
# print all the values in a list without using a for loop
fruits=['orange', 'apple', 'banana', 'tomato', 'lime', 'lemon']
print(fruits[0])
print(fruits[1])
print(fruits[2])
print(fruits[3])
print(fruits[4])
print(fruits[5])

In [ ]:
# print all the values in a list using a for loop
for f in fruits:
    print(f)

You can easily see that **the second cell is a much more efficient way to code**. It is not only shorter, but it is less error-prone. Errors in the code (**bugs**) are the worst nightmare of a data analyst. Again, note the **indentation** of the line containing `print(f)`. Try removing the indenting spaces. Can you then run that cell?

In this case one only needs to write 6 lines of code for the first cell to get all the fruits, but what if we had 1,000 fruits?... Then we would have had to write 1,000 lines!.
On the other hand, in the second cell we just needed two lines of code, both for 6 and 1,000 fruits.
Everytime you see yourself repeating the same code just to change a small detail, remember you can use [for loops](https://www.w3schools.com/python/python_for_loops.asp)


Let's use the foor loop in our dataset!
***Make the error histogram for each subject***  

Hint 1: Take advantage of the code you used before to get the data of Subject #7, and now generalize to all other subjects.  

Hint 2: To iterate through subjects you need to get the list of indexes for the subjects. To get that list you can use [`np.unique()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.unique.html) if you are not sure about how many subjects there are, or else use [`np.arange()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html) to get a range of values. Now you are ready to start your for loop.

Hint 3: write: `plt.figure()` at the beginning of every iteration so you generate one histogram for each subject.

Hint 4: Remember to enter 4 indenting spaces in front of the commands within the for loop!


In [ ]:
# create plot with one subplot per subject
nColumns = 3
nRows = int(np.ceil(nSubject/nColumns))
fig, ax = plt.subplots(nRows, nColumns, figsize=(14, 16))

# loop through subjects
for sb in ???:

    # define boolean array that is true for rows corresponding to this subject
    trials = ???

    # subplot counter (integer starting at 0, could also be done better using enumerate)
    i = int(sb-1)
    iCol = i % nColumns # corresponding column
    iRow = i// nColumns # corresponding row

    # add histogram for this subject
    ax[iRow,iCol].???;

    # add vertical line
    mean_error = ??? # mean error for this subject
    ax[iRow,iCol].axvline(mean_error, color='red');

    # add label and title
    ax[iRow,iCol].set_xlim((-100,100))
    ax[iRow,iCol].set_ylabel('trial count')
    ax[iRow,iCol].set_title(f'Subject: {int(sb)}')

# Panda DataFrames

You are now ready to do manipulations and graphical representations on your data, using the basic features of the **numpy** and **matplotplib** packages.

However, in modern data analyses with Python it is common to use another library to organize better the data and provide more robust and intuitive subsetting and manipulation of the data. This is the [pandas](https://pandas.pydata.org/docs/getting_started/index.html#getting-started) library, and it introduces the concept of **DataFrame**.

Dataframes also organize the data in rows and columns, but they naturally index them with names, rather than index numbers. Each row will generally correspond to one observation (here, on trial), and each column corresponds to one variable (stimulus, response, subject identity, etc.). This way, we can write our code referring to column `'error'` instead of column `5` and this makes debugging much easier. In addition, they come equipped with many in-built functions for compact data manipulation that make it a very powerful tool - we will only scratch the surfance of all the possibilities offered by dataframes.

So, to start using Pandas, we need to import the library:

In [ ]:
import pandas as pd

and now we need to build our DataFrame. Since we already have a matrix with our data, we can just generate the DataFrame from this matrix by specifying the names of each column:

In [ ]:
df = pd.DataFrame(data, columns=['x1', 'x2', 'xavg', 'estim', 'subject', 'error'])

Note that we could also directly load the data in a DataFrame from a CSV file, using the command below.
The benefits of importing directly is that we also direct get the columns names from the CSV, we do have to specify them.
(Of course we would also need to add the Error column)

In [ ]:
#df = pd.read_csv("Task_Perceptual_simple.csv",sep=',')

You can now see the first rows of this dataframe using the command `head`:

In [ ]:
df.head()

Notice that now we use our dataframe as if it were a "library" from which we call functions: `df.fun` means that we apply built-in panda function `fun` to the dataframe `df`. There are tons of functions defined for Pandas dataframes and this is the extraordinary power of this library.

Now, instead of getting error values with `data[:,-1]`, we can use `df['error']`. This is a significant change because our code may add columns inadvertently and then `data[:,-1]` may be addressing something different than "error" but `df['error']` is clearly always getting back what we want. In this sense, our code will be clearer and have fewer bugs. Convince yourself that `data[:,-1]` and `df['error']` now give the same list of values:

In [ ]:
???

In [ ]:
???

As an exercise: **add now one extra column to the dataframe df that contains the circular distance between the columns x1 and x2**. This is much easier than with `column_stack` in plain **numpy**, you just need to assign the new values to a new column name (for instance `df['dist_x1x2']`) Check with `df.head()` that you can see this new column in your table.

In [ ]:
???
df.head()

Well done! Now compare the simplicity of adding one column to a dataframe to the more cumbersome way to append a column to a numpy array as we did above using `np.column_stack`

Now check this:

In [ ]:
df.hist(column='error', by='subject');

**Neat, eh?** Compare what you had to do with bare **numpy** above!! You can unpack this very compact command [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.hist.html).

It is thus general good practice to organize our datasets in Python using the Pandas library. It not only keeps the code more readable, and prevents many errors, but it also provides very compact functions to deal with data manipulation and plotting. See for instance how you would compute the mean and standard deviation of behavioral errors for each subject:

In [ ]:
df.groupby('subject').error.agg(('mean', 'std'))